debug

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -83,11 +83,10 @@ runs:
       id: create-branch
       shell: bash
       run: |
-        echo 'annotation debug: ${{ inputs.annotation }}'
         # validate and convert annotation to map[string]string
         if [[ -n "${{ inputs.annotation }}" ]]; then
           annotation=$(echo "${{ inputs.annotation }} | jq -r \
-          'if type!="object" then "" else with_entries(.key |= "github-\(.)") | with_entries(.value |= (.|tostring)) end')
+          'if type!="object" then "" else with_entries(.key |= "github-\(.)") | with_entries(.value |= (.|tostring)) end') || echo "failed to validate annotation"
           echo "annotation: ${{ inputs.annotation }}, processed: ${annotation}"
         fi
         
