fixing silent fail

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -24,7 +24,7 @@ inputs:
   prisma:
     description: 'Use prisma or not'
     default: 'false'
-  suspend_timeout: 
+  suspend_timeout:
     description: >
       Duration of inactivity in seconds after which the compute endpoint is
       For more information, see [Auto-suspend configuration](https://neon.tech/docs/manage/endpoints#auto-suspend-configuration).
@@ -88,6 +88,9 @@ runs:
           NEON_CS_POOLER=$(neonctl cs ${branch_id} --project-id ${{ inputs.project_id }} --role-name ${{ inputs.username }} --database-name ${{ inputs.database }} --pooled --prisma ${{ inputs.prisma }} --extended -o json)
           DB_URL_WITH_POOLER=$(echo $NEON_CS_POOLER | jq -r '.connection_string')
           DB_HOST_WITH_POOLER=$(echo $NEON_CS_POOLER | jq -r '.host')
+        elif [[ $(cat branch_err) == "ERROR:"* ]]; then
+          echo "::error branch create failed, branch err: $(cat branch_err)\n"
+          exit 1
         else
           branch_id=$(cat branch_out | jq --raw-output '.branch.id')
 
