Fix skipping multiline error (#28)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -91,12 +91,16 @@ runs:
           NEON_CS_POOLER=$(neonctl cs ${branch_id} --project-id ${{ inputs.project_id }} --role-name ${{ inputs.username }} --database-name ${{ inputs.database }} --pooled --prisma ${{ inputs.prisma }} --extended -o json)
           DB_URL_WITH_POOLER=$(echo $NEON_CS_POOLER | jq -r '.connection_string')
           DB_HOST_WITH_POOLER=$(echo $NEON_CS_POOLER | jq -r '.host')
-        elif [[ $(cat branch_err) == "ERROR:"* ]]; then
+        elif [[ $(cat branch_err) == *"ERROR:"* ]]; then
           echo "ERROR: branch creation failed"
           cat branch_err
           exit 1
         else
           branch_id=$(cat branch_out | jq --raw-output '.branch.id')
+          if [[ -z "${branch_id}" ]]; then
+            echo "ERROR: didn't get the branch id"
+            exit 1
+          fi
 
           echo "branch doesn't exist, branch id: ${branch_id}\n" >> debug.log
 
