Fix silent fail (#26)

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -26,7 +26,7 @@ inputs:
     default: 'false'
   parent:
     description: 'The parent branch name or id or LSN or timestamp . By default the primary branch is used'
-  suspend_timeout: 
+  suspend_timeout:
     description: >
       Duration of inactivity in seconds after which the compute endpoint is
       For more information, see [Auto-suspend configuration](https://neon.tech/docs/manage/endpoints#auto-suspend-configuration).
@@ -69,7 +69,11 @@ runs:
           --output json \
           2> branch_err > branch_out || true
 
-        echo "branch created:\n" >> debug.log
+        echo "branch create out:\n" >> debug.log
+        cat branch_out >> debug.log
+        echo "\nbranch create err:\n" >> debug.log
+        cat branch_err >> debug.log
+        echo "\n" >> debug.log
 
         if [[ $(cat branch_err) == *"already exists"* ]]; then
 
@@ -87,6 +91,10 @@ runs:
           NEON_CS_POOLER=$(neonctl cs ${branch_id} --project-id ${{ inputs.project_id }} --role-name ${{ inputs.username }} --database-name ${{ inputs.database }} --pooled --prisma ${{ inputs.prisma }} --extended -o json)
           DB_URL_WITH_POOLER=$(echo $NEON_CS_POOLER | jq -r '.connection_string')
           DB_HOST_WITH_POOLER=$(echo $NEON_CS_POOLER | jq -r '.host')
+        elif [[ $(cat branch_err) == "ERROR:"* ]]; then
+          echo "ERROR: branch creation failed"
+          cat branch_err
+          exit 1
         else
           branch_id=$(cat branch_out | jq --raw-output '.branch.id')
 
